/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.demo.ui;

import com.demo.controller.controllerArticulo;
import com.demo.design.validacion;
import com.demo.dominio.Articulo;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jona
 */
public class frmIntFactura extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmIntFactura
     */
    private validacion validacion = new validacion();
    private Character kpress;
    private controllerArticulo ctrlarticulo;
    private Articulo articulo; 
    
    public frmIntFactura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_iva = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_facturaDetalle = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txt_subtotal = new javax.swing.JTextField();
        txt_totalpagar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_cantidadFactura = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();
        comboBox_producto = new javax.swing.JComboBox<>();
        btn_buscar = new javax.swing.JButton();
        btn_limpiar2 = new javax.swing.JButton();
        btn_eliminar1 = new javax.swing.JButton();
        comboBox_nombre1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txt_precioUnit = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_nombreProv6 = new javax.swing.JTextField();

        setClosable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Factura ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 16))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_iva.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txt_iva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ivaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_iva, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 100, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setText("Nombre:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        tabla_facturaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Descripción", "Precio Unitario"
            }
        ));
        jScrollPane1.setViewportView(tabla_facturaDetalle);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 680, 120));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel7.setText("Producto: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txt_subtotal.setEditable(false);
        txt_subtotal.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txt_subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_subtotalActionPerformed(evt);
            }
        });
        jPanel1.add(txt_subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 100, -1));

        txt_totalpagar.setEditable(false);
        txt_totalpagar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txt_totalpagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalpagarActionPerformed(evt);
            }
        });
        jPanel1.add(txt_totalpagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 100, -1));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel9.setText("Cantidad:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        txt_cantidadFactura.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txt_cantidadFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantidadFacturaActionPerformed(evt);
            }
        });
        txt_cantidadFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cantidadFacturaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cantidadFacturaKeyTyped(evt);
            }
        });
        jPanel1.add(txt_cantidadFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 230, -1));

        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/demo/imagenes/btnguardar.png"))); // NOI18N
        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        comboBox_producto.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        comboBox_producto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBox_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_productoActionPerformed(evt);
            }
        });
        jPanel1.add(comboBox_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 230, -1));

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        btn_limpiar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/demo/imagenes/btneditar.png"))); // NOI18N
        btn_limpiar2.setText("Nuevo");
        btn_limpiar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiar2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_limpiar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        btn_eliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/demo/imagenes/btneliminar.png"))); // NOI18N
        btn_eliminar1.setText("Eliminar");
        btn_eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_eliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        comboBox_nombre1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        comboBox_nombre1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboBox_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 230, -1));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel10.setText("Precio Unitario: ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        txt_precioUnit.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txt_precioUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_precioUnitActionPerformed(evt);
            }
        });
        jPanel1.add(txt_precioUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 230, -1));

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel11.setText("Total a pagar: ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 90, -1));

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel13.setText("Subtotal:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 60, -1));

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel14.setText("Iva:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 30, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 410));

        txt_nombreProv6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txt_nombreProv6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreProv6ActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nombreProv6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 230, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ivaActionPerformed

    private void txt_nombreProv6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreProv6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreProv6ActionPerformed

    private void txt_subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_subtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_subtotalActionPerformed

    private void txt_totalpagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalpagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalpagarActionPerformed

    private void txt_cantidadFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidadFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantidadFacturaActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model1= (DefaultTableModel) tabla_facturaDetalle.getModel();
         Object[] row = new Object[6];
         row[0] = txt_cantidadFactura.getText();
         row[1] = comboBox_producto.getSelectedItem(); 
         row[2] = txt_precioUnit.getText();
         row[3]= txt_total.getText();
         model1.addRow(row);
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_limpiar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiar2ActionPerformed
        // TODO add your handling code here:
        
        habilitar();
        comboBox_nombre1.requestFocus();
        comboBox_producto.requestFocus();
        txt_cantidadFactura.requestFocus();
        txt_precioUnit.requestFocus();
        limpiar();
    }//GEN-LAST:event_btn_limpiar2ActionPerformed

    private void btn_eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model= (DefaultTableModel) tabla_facturaDetalle.getModel();
        int filas;
        if (model.getRowCount()>0){
            if(tabla_facturaDetalle.getSelectedRow()!=-1){
                filas = tabla_facturaDetalle.getSelectedRow();
                model.removeRow(filas);
                //calTotal();
            }else{
                JOptionPane.showConfirmDialog(null,"Seleccione una fila");
            }
        }else {
            JOptionPane.showConfirmDialog(null,"No hay filas");
        }
    }//GEN-LAST:event_btn_eliminar1ActionPerformed

    private void txt_precioUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_precioUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_precioUnitActionPerformed

    private void comboBox_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBox_productoActionPerformed

    private void txt_cantidadFacturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cantidadFacturaKeyPressed
        // TODO add your handling code here:
        kpress = evt.getKeyChar();
        if (kpress == KeyEvent.VK_ENTER) {
            txt_cantidadFactura.transferFocus();
        }
        
    }//GEN-LAST:event_txt_cantidadFacturaKeyPressed

    private void txt_cantidadFacturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cantidadFacturaKeyTyped
        // TODO add your handling code here:
        validacion.soloNumeros(evt);
    }//GEN-LAST:event_txt_cantidadFacturaKeyTyped
    void habilitar() {
        comboBox_nombre1.enable(true);
        comboBox_producto.enable(true);
        txt_cantidadFactura.enable(true);
        txt_precioUnit.enable(true);
    }

    void limpiar() {
            comboBox_nombre1.setSelectedItem("");
            comboBox_producto.setSelectedItem("");
            txt_precioUnit.setText("");
            txt_cantidadFactura.setText("");
        }
    
    void calTotal(){
        double S=0;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_eliminar1;
    private javax.swing.JButton btn_limpiar2;
    private javax.swing.JComboBox<String> comboBox_nombre1;
    private javax.swing.JComboBox<String> comboBox_producto;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_facturaDetalle;
    private javax.swing.JTextField txt_cantidadFactura;
    private javax.swing.JTextField txt_iva;
    private javax.swing.JTextField txt_nombreProv6;
    private javax.swing.JTextField txt_precioUnit;
    private javax.swing.JTextField txt_subtotal;
    private javax.swing.JTextField txt_totalpagar;
    // End of variables declaration//GEN-END:variables

    
    void buscar(String nombre) {
        limpiarTabla();
        ctrlarticulo = new controllerArticulo();
        List<Articulo> lista = ctrlarticulo.verArticulos(nombre);
        DefaultTableModel model1 = (DefaultTableModel) tabla_facturaDetalle.getModel();
        for (Articulo articulo : lista) {
            ///hacer uso de tabla
            Object[] row = new Object[12];
            row[1] = articulo.getDescripcion();
            row[2] = articulo.getPrecio_venta();
            model1.addRow(row);
        }

    }
    void limpiarTabla(){	
	DefaultTableModel model1 = (DefaultTableModel) tabla_facturaDetalle.getModel();
        model1.setRowCount(0);
	}

}


